name: polymer_intl
description: Open Race Timing
homepage: https://github.com/skoky/OpenRaceTiming
environment:
  sdk: '>=1.0.0 <2.0.0'
documentation: https://github.com/skoky/OpenRaceTiming/wiki
dependencies:
  intl: '>=0.11.6 <0.12.0'
  polymer: '>=0.13.0 <0.14.0'
  unittest: any
transformers:
- polymer:
    entry_points: web/index.html
