name: OpenRaceTimingTest
description: A sample command-line application
dependencies:
  event_commander: any
  browser: any
  bwu_datagrid: ">=0.0.18 <0.1.0"
  polymer: '>=0.12.1 <0.16.0'

transformers:
- polymer:
    entry_points:
    - web/ort_event_main.html  